import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import QueryProvider from "@/providers/QueryProvider";
import { AuthProvider } from "@/context/AuthContext";
import Sidebar from "./Sidebar";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${robotoMono.variable} antialiased`}>
        <Sidebar />
        <AuthProvider>
          <QueryProvider>
            <div className="mt-16">{children}</div>
          </QueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
